version: '3.8'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

  frontend:
    build:
      context: ./Fronttend
      dockerfile: dockerfile
    ports:
      - "5173:5173"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
