version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: restaurante
      MYSQL_USER: alumno
      MYSQL_PASSWORD: alumnoipm
    ports:
      - "3307:3306"


  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    depends_on:
      - mysql
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      URL: ${URL}
      DB_NAME: ${DB_NAME}
      PORT_FRONT: ${PORT_FRONT}
      PORT_BACK: ${PORT_BACK}
    ports:
      - "${PORT_BACK}:${PORT_BACK}"
    restart: unless-stopped

  frontend:
    build:
      context: ./Fronttend     
      dockerfile: Dockerfile
    environment:
      URL: ${URL}
      PORT_FRONT: ${PORT_FRONT}
      PORT_BACK: ${PORT_BACK}
    ports:
      - "${PORT_FRONT}:${PORT_NGINX}"
    depends_on:
      - backend

